force-app/main/default/objects/DHKT_Request__c/DHKT_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>RQS-{0000000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHKT_Request__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <formula>Student__r.Activity_Class__r.Name</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Student__r.Email__c</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>DHKT_Faculty__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Faculty_Name__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Name__c</fullName>
    <formula>Faculty__r.Name</formula>
    <label>Faculty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>DHKT_Major__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <formula>Student__r.Phone_Number__c</formula>
    <label>Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Request_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Request_Header</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Date__c</fullName>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student Id</label>
    <referenceTo>DHKT_Student__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <formula>Student__r.Student_Name__c</formula>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Submitting_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Date__c</fullName>
    <label>Submitting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/DHKT_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STD-{0000000000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHKT_Student__c/fields/Activity_Class__c.field-meta.xml
<CustomField>
    <fullName>Activity_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Class</label>
    <referenceTo>DHKT_Activity_Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>DHKT_Faculty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>DHKT_Major__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DHKT_RequestController.cls
/**
 * @description       :
 * @author            : Ba Truong Nguyen
 * @group             :
 * @last modified on  : 04-02-2023
 * @last modified by  : Ba Truong Nguyen
 **/
public with sharing class DHKT_RequestController {
  @AuraEnabled
  public static List<DHKT_Request__c> getRequest(String recordId) {
    try {
      return [
        SELECT
          Id,
          Name,
          Major__c,
          Faculty__c,
          Student__c,
          Due_date__c,
          Note__c,
          Reject_Reason__c,
          Return_Date__c,
          Submitting_Date__c,
          Request_Header__c,
          Request_Type__c,
          Request_Status__c,
          (
            SELECT
              Id,
              Name,
              Facility_Name__c,
              Zone_Area__c,
              Classroom__c,
              Facility_Code__c
            FROM Facilities__r
          )
        FROM DHKT_Request__c
        WHERE Id = :recordId
      ];
    } catch (Exception e) {
      throw new AuraHandledException(
        'Can not get request data: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static List<DHKT_Facility__c> getFacilityRecords(String requestId) {
    try {
      return [
        SELECT
          Id,
          Name,
          Facility_Name__c,
          Zone_Area__c,
          Classroom__c,
          Facility_Code__c
        FROM DHKT_Facility__c
        WHERE Request__c = :requestId
      ];
    } catch (Exception e) {
      throw new AuraHandledException(
        'Can not get facility data: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static List<DHKT_Facility__c> getFacilityOptions(String requestId) {
    try {
      return [
        SELECT Facility_Code__c
        FROM DHKT_Facility__c
        WHERE
          Request__c = :requestId
          OR Request__c = NULL
          OR Request__r.Request_Status__c = 'Finalized'
      ];
    } catch (Exception e) {
      throw new AuraHandledException(
        'Can not get facility options: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static DHKT_Student__c getCurrentUserData() {
    try {
      String currentUserId = UserInfo.getUserId();
      User currentUser = [
        SELECT Id, Name, Profile.Name, Email
        FROM User
        WHERE Id = :currentUserId
      ];
      String studentName = '%' + currentUser?.Name + '%';

      DHKT_Student__c student = [
        SELECT
          Id,
          Name,
          Activity_Class__c,
          Class_Name__c,
          Faculty__c,
          Faculty_Name__c,
          Major__c,
          Major_Name__c,
          Date_of_Birth__c,
          Phone_Number__c,
          Email__c,
          Student_Name__c,
          Subject__c
        FROM DHKT_Student__c
        WHERE Email__c = :currentUser.Email
        ORDER BY CreatedDate DESC
        LIMIT 1
      ];
      return student;
    } catch (Exception e) {
      System.debug('Fail to get Student Information: ' + e.getMessage());
      return null;
    }
  }

  @AuraEnabled
  public static Boolean saveFacilityOptions(
    String facilitiesArray,
    String requestId
  ) {
    System.debug('facilitiesArray: ' + facilitiesArray);
    System.debug('requestId: ' + requestId);

    try {
      List<Facility> facilities = (List<Facility>) JSON.deserialize(
        facilitiesArray,
        List<Facility>.class
      );
      System.debug('facilities: ' + facilities);

      for (Facility facility : facilities) {
        DHKT_Facility__c f = [
          SELECT
            Id,
            Name,
            Facility_Name__c,
            Zone_Area__c,
            Classroom__c,
            Request__c,
            Facility_Code__c
          FROM DHKT_Facility__c
          WHERE Facility_Code__c = :facility.facilityCode
        ];
        f.Facility_Name__c = facility.facilityName;
        f.Zone_Area__c = facility.zoneArea;
        f.Classroom__c = facility.classroom;
        f.Request__c = requestId;
        update f;
      }
      return true;
    } catch (Exception e) {
      System.debug('Fail to save this Request: ' + e.getMessage());
      return false;
    }
  }

  public class Facility {
    public String facilityCode { get; set; }
    public String facilityName { get; set; }
    public String zoneArea { get; set; }
    public String classroom { get; set; }
  }
}