force-app/main/default/objects/DHKT_Notification__c/DHKT_Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000000000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHKT_Notification__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/DHKT_Notification__c/fields/Body_Plain_Text__c.field-meta.xml
<CustomField>
    <fullName>Body_Plain_Text__c</fullName>
    <label>Body Plain Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHKT_Notification__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>DHKT_Faculty__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Notification__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Notification__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>DHKT_Student__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Notification__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>DHKT_Teacher__c</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/DHKT_Request__c.object-meta.xml
<CustomObject>
    <label>Request</label>
    <nameField>
        <displayFormat>RQS-{0000000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHKT_Request__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <formula>Student__r.Activity_Class__r.Name</formula>
    <label>Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Cumulative_Credits__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Credits__c</fullName>
    <label>Cumulative Credits</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Day_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Birth__c</fullName>
    <formula>Student__r.Date_of_Birth__c</formula>
    <label>Day of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Student__r.Email__c</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>DHKT_Faculty__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Faculty_Name__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Name__c</fullName>
    <formula>Faculty__r.Name</formula>
    <label>Faculty</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Is_My_Request__c.field-meta.xml
<CustomField>
    <fullName>Is_My_Request__c</fullName>
    <formula>CreatedBy.Username = $User.Username</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is My Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>DHKT_Major__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <formula>Student__r.Phone_Number__c</formula>
    <label>Phone Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Report_Registration_Method__c.field-meta.xml
<CustomField>
    <fullName>Report_Registration_Method__c</fullName>
    <label>Report Registration Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internship Report</fullName>
            </value>
            <value>
                <fullName>Thesis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Header__c.field-meta.xml
<CustomField>
    <fullName>Request_Header__c</fullName>
    <label>Request Header</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Request_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Request_Header</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Request_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Date__c</fullName>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student Id</label>
    <referenceTo>DHKT_Student__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <formula>Student__r.Student_Name__c</formula>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHKT_Request__c/fields/Submitting_Date__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Date__c</fullName>
    <label>Submitting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/DHKT_Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>STD-{0000000000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHKT_Student__c/fields/Activity_Class__c.field-meta.xml
<CustomField>
    <fullName>Activity_Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Class</label>
    <referenceTo>DHKT_Activity_Class__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/fields/Faculty__c.field-meta.xml
<CustomField>
    <fullName>Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faculty</label>
    <referenceTo>DHKT_Faculty__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHKT_Student__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Major</label>
    <referenceTo>DHKT_Major__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DHKT_StudentAppController.cls
/**
 * @description       :
 * @author            : Ba Truong Nguyen
 * @group             :
 * @last modified on  : 06-16-2023
 * @last modified by  : Ba Truong Nguyen
 **/
public without sharing class DHKT_StudentAppController {
  @AuraEnabled
  public static String getStudentInfoForCurrentUser() {
    try {
      String currentUserId = UserInfo.getUserId();
      User currentUser = [
        SELECT Id, Name, Profile.Name, Email
        FROM User
        WHERE Id = :currentUserId
      ];
      String studentName = '%' + currentUser?.Name + '%';

      DHKT_Student__c student = [
        SELECT
          Id,
          Name,
          CreatedDate,
          Activity_Class__c,
          Faculty__c,
          Major__c,
          Date_of_Birth__c,
          Phone_Number__c,
          Email__c,
          Student_Name__c,
          CreatedById,
          (
            SELECT
              Id,
              Name,
              CreatedDate,
              Major__c,
              Faculty__c,
              Student__c,
              Due_date__c,
              Note__c,
              Reject_Reason__c,
              Return_Date__c,
              Submitting_Date__c,
              Request_Header__c,
              Request_Type__c,
              Request_Status__c,
              Faculty_Name__c,
              Day_of_Birth__c,
              Class_Name__c,
              Student_Name__c,
              Phone_Number__c,
              Email__c,
              Reason__c,
              Cumulative_Credits__c,
              Report_Registration_Method__c,
              Is_My_Request__c
            FROM Requests__r
            ORDER BY CreatedDate DESC
          )
        FROM DHKT_Student__c
        WHERE Email__c = :currentUser.Email
        ORDER BY Id DESC
        LIMIT 1
      ];
      return JSON.serialize(student);
    } catch (Exception e) {
      System.debug('Cannot get student infomation: ' + e.getMessage());
      return null;
    }
  }

  @AuraEnabled
  public static string getNotifications() {
    try {
      DHKT_Student__c student = DHKT_RequestController.getCurrentUserData();

      Notification notifications = new Notification();
      List<DHKT_Notification__c> notificationQueries = [
        SELECT
          Id,
          Name,
          CreatedDate,
          Student__c,
          Teacher__c,
          Faculty__c,
          Body__c,
          From__c,
          Title__c,
          Activity_Class__c,
          Body_Plain_Text__c
        FROM DHKT_Notification__c
        WHERE
          Faculty__c = :student.Faculty__c
          OR Activity_Class__c = :student.Activity_Class__c
          OR Student__c = :student.Id
        ORDER BY CreatedDate DESC
      ];
      List<DHKT_Notification__c> facultyNotifications = new List<DHKT_Notification__c>();
      List<DHKT_Notification__c> classNotifications = new List<DHKT_Notification__c>();
      List<DHKT_Notification__c> personalNotifications = new List<DHKT_Notification__c>();
      for (DHKT_Notification__c noti : notificationQueries) {
        if (noti.Faculty__c == student.Faculty__c) {
          facultyNotifications.add(noti);
        } else if (noti.Activity_Class__c == student.Activity_Class__c) {
          classNotifications.add(noti);
        } else if (noti.Student__c == student.Id) {
          personalNotifications.add(noti);
        }
      }
      notifications.facultyNotifications = facultyNotifications;
      notifications.classNotifications = classNotifications;
      notifications.personalNotifications = personalNotifications;
      System.debug('List Notifications: ' + notifications);
      return JSON.serialize(notifications);
    } catch (Exception e) {
      System.debug('Error getting notification: ' + e.getMessage());
      return null;
    }
  }

  @AuraEnabled
  public static string getStudentInfo() {
    try {
      DHKT_Student__c student = DHKT_RequestController.getCurrentUserData();
      return JSON.serialize(student);
    } catch (Exception e) {
      System.debug('Cannot get student infomation: ' + e.getMessage());
      return null;
    }
  }

  public class Notification {
    public List<DHKT_Notification__c> facultyNotifications;
    public List<DHKT_Notification__c> classNotifications;
    public List<DHKT_Notification__c> personalNotifications;
  }
  public class Request {
    public List<DHKT_Request__c> requests;
  }
}